Vagrant.configure("2") do |config|
    # Box do Ubuntu 20.04 (focal)
    config.vm.box = "ubuntu/focal64"
  
    # Configuração de rede para acesso à aplicação Laravel
    config.vm.network "private_network", type: "dhcp"
  
    # Sincronizar a pasta do host com a VM (opcional)
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
    # Provisionamento usando o script de shell
    config.vm.provision "shell", path: "provision.sh"
  
    # Encaminhamento de porta para acessar o Laravel pela máquina host
    config.vm.network "forwarded_port", guest: 8000, host: 8000
  end
  